### ISSUE TITLE
[Question] How to use this module

### ISSUE THREAD

**Issue by s3n-w6i** [hobbyquaker/scene-sequencer#1]
I am pretty new to JavaScript and I would like to know how to use this module in conjunction with [hobbyquaker/artnet](https://github.com/hobbyquaker/artnet). So, in detail:
1) How to input the sequence data correctly and control the playback (play/pause, ...)
2) How to get this data and feed it to the artnet output

Any help would be really appreciated. Thank you!

**Comment by hobbyquaker** [comment]
Sorry for the long delay...

I'm using this module in these projects: 
* https://github.com/hobbyquaker/mqtt-dmx-controller
* https://github.com/hobbyquaker/mqtt-dmx-sequencer

so you could look at their code for an usage example.

Sorry to say that I have not documented anything here, never thought that someone else could be interested in this module ;)

**Comment by s3n-w6i** [comment]
Thanks 👍
